const PLAN=[
{day:'Montag',name:'Upper A + Arme',type:'strength',ex:[['Schrägbankdrücken',3,6,8,'compound'],['Klimmzüge / Latzug',3,6,8,'compound'],['Bankdrücken',3,6,8,'compound'],['Brustgestütztes Rudern',3,8,10,'compound'],['Cable Fly',2,10,15,'iso'],['Seitheben',3,10,15,'iso'],['Preacher Curls',3,6,10,'iso'],['Trizeps Pushdown',3,6,10,'iso']]},
{day:'Dienstag',name:'Lower A',type:'strength',ex:[['Kniebeugen',3,5,8,'compound'],['Beinpresse',3,8,12,'compound'],['Beinbeuger',3,8,12,'iso'],['Beinstrecker',2,10,15,'iso'],['Wadenheben',3,8,15,'iso'],['Cable Crunches',3,8,15,'iso']]},
{day:'Mittwoch',name:'Zone 2',type:'run',duration:'30–45 min locker'},
{day:'Donnerstag',name:'Upper B + Arme',type:'strength',ex:[['Bankdrücken',3,5,8,'compound'],['Breites Rudern',3,6,10,'compound'],['Schrägbank Kurzhanteln',2,8,12,'compound'],['Latzug',3,8,12,'compound'],['Schulterdrücken',2,6,10,'compound'],['Reverse Fly',2,12,15,'iso'],['Seitheben',3,10,15,'iso'],['Incline DB / Bayesian Curl',3,8,12,'iso'],['Overhead Cable Triceps Extension',3,8,12,'iso']]},
{day:'Freitag',name:'Lower B',type:'strength',ex:[['Romanian Deadlift',3,6,10,'compound'],['Hack Squat / Beinpresse',3,8,10,'compound'],['Bulgarian Split Squat',2,8,12,'compound'],['Beinbeuger',3,8,12,'iso'],['Beinstrecker',2,10,15,'iso'],['Wadenheben',3,10,15,'iso'],['Bauch',3,10,15,'iso']]},
{day:'Samstag',name:'Arms + Shoulders',type:'strength',ex:[['Preacher Curl',3,6,10,'iso'],['Hammer Curl',3,8,12,'iso'],['Cable Pushdown',3,6,10,'iso'],['Overhead Triceps Extension',3,8,12,'iso'],['Seitheben',4,10,15,'iso'],['Reverse Fly',3,12,15,'iso'],['Cable Crunches',3,8,15,'iso']]},
{day:'Sonntag',name:'Zone 2 / Recovery',type:'run',duration:'30–45 min locker, optional'}];
const K='kg85tracker-v1';let db=JSON.parse(localStorage.getItem(K)||'{"weight":[{"date":"'+new Date().toISOString().slice(0,10)+'","kg":78}],"sessions":[],"runs":[]}');let view='home',selected=(new Date().getDay()+6)%7,timer=null,timerLeft=0;const save=()=>localStorage.setItem(K,JSON.stringify(db));const el=()=>document.getElementById('app');
function lastWeight(){return db.weight.length?db.weight[db.weight.length-1].kg:78}function lastExercise(name){for(let i=db.sessions.length-1;i>=0;i--){let x=db.sessions[i].exercises?.find(e=>e.name===name);if(x)return x}return null}function today(){let d=new Date(),o=d.getTimezoneOffset();return new Date(d-o*60000).toISOString().slice(0,10)}function volume(s){return (s.exercises||[]).flatMap(e=>e.sets||[]).reduce((a,x)=>a+(+x.kg||0)*(+x.reps||0),0)}function bestSet(e){return Math.max(0,...(e?.sets||[]).map(s=>(+s.kg||0)*(1+(+s.reps||0)/30)))}function previousBest(name,current){return Math.max(0,...db.sessions.filter(x=>x!==current).flatMap(x=>(x.exercises||[]).filter(e=>e.name===name).map(bestSet)))}function sessionPRs(s){return (s.exercises||[]).filter(e=>bestSet(e)>0&&bestSet(e)>previousBest(e.name,s)).length}
function nav(){return `<div class='nav'><div class='navin'>${[['home','Heute'],['plan','Plan'],['progress','Fortschritt'],['data','Daten']].map(x=>`<button class='${view===x[0]?'active':''}' onclick="view='${x[0]}';render()">${x[1]}</button>`).join('')}</div></div>`}
function header(){return `<div class='top'><div><div class='brand'><span>85</span>KG</div><div class='sub'>Hypertrophy Tracker</div></div></div><div id='restFloat' class='restfloat ${timerLeft?'show':''}'><span class='restlabel'>PAUSE</span><b id='timer'>${timerLeft?fmt(timerLeft):''}</b><button onclick='stopTimer()'>Überspringen</button></div>`}
function days(){return `<div class='days'>${PLAN.map((d,i)=>`<div class='day ${i===selected?'active':''}' onclick='selected=${i};view="plan";render()'><b>${d.day.slice(0,2)}</b><span>${d.name}</span></div>`).join('')}</div>`}
function home(){let w=lastWeight(),pct=Math.max(0,Math.min(100,(w-78)/(84.5-78)*100));return `<div class='grid'><div class='card hero'><div class='kicker'>Heute</div><h1>${PLAN[selected].name}</h1><p class='muted'>${PLAN[selected].type==='run'?PLAN[selected].duration:(PLAN[selected].ex.length+' Übungen')}</p><button class='btn' onclick='view="plan";render()'>Einheit öffnen</button></div><div class='card'><div class='kicker'>Aufbauziel</div><div class='big'>${w.toFixed(1)} kg</div><p class='muted'>Ziel 84–85 kg</p><div class='progress'><i style='width:${pct}%'></i></div></div></div>${days()}<h2 style='margin-top:22px'>Letzte Fortschritte</h2><div class='card'>${db.sessions.length?db.sessions.slice(-3).reverse().map(s=>`<div class='history'><b>${s.name}</b><div class='muted'>${s.date}</div></div>`).join(''):'Noch kein Krafttraining gespeichert.'}</div>`}
function strength(d){return `<div class='workoutbar'><div><h1 style='margin-bottom:4px'>${d.name}</h1><p class='muted' style='margin-bottom:0'>Satz abhaken → Pausentimer startet automatisch</p></div><details class='switcher'><summary>Einheit wechseln</summary>${days()}</details></div><div id='workout'>${d.ex.map((x,ei)=>exercise(x,ei)).join('')}</div><div class='finishbar'><button class='btn' onclick='finishWorkout()'>Training speichern</button></div>`}
function exercise(x,ei){let [name,n,min,max,type]=x,last=lastExercise(name),hint='';if(last){let allTop=last.sets?.length>=n&&last.sets.slice(0,n).every(s=>+s.reps>=max&&+s.rir<=2);hint=allTop?`Gewicht leicht erhöhen – Rep-Range letztes Mal komplett erreicht.`:`Letztes Training als Vorlage`;}
return `<div class='exercise' data-ei='${ei}' data-name='${name}' data-type='${type}'><div class='exhead'><div><b>${name}</b><div class='muted'>${n} × ${min}–${max}</div></div><span class='pill'>${type==='compound'?'1–2 RIR · 3:00':'0–2 RIR · 1:30'}</span></div>${hint?`<div class='target ${hint.startsWith('Gewicht')?'good':''}'>${hint}</div>`:''}<div class='setlabels'><span>Satz</span><span>kg</span><span>Reps</span><span>RIR</span><span></span></div><div class='sets'>${Array.from({length:n},(_,si)=>{let prev=last?.sets?.[si]||{},prevTxt=prev.kg||prev.reps?`${prev.kg||0} × ${prev.reps||0}${prev.rir!==''&&prev.rir!=null?` · RIR ${prev.rir}`:''}`:'—';return `<div class='setwrap'><div class='prevset'>Letztes Mal: ${prevTxt}</div><div class='setrow'><b>${si+1}</b><input inputmode='decimal' class='kg' aria-label='Kilogramm' placeholder='kg' value='${prev.kg??''}'><input inputmode='numeric' class='reps' aria-label='Wiederholungen' placeholder='Reps'><input inputmode='numeric' class='rir' aria-label='RIR' placeholder='RIR'><button class='check' aria-label='Satz fertig' onclick='completeSet(this,"${type}")'>✓</button></div></div>`}).join('')}</div><div class='field'><input class='note' placeholder='Notiz zur Übung'></div></div>`}
function completeSet(btn,type){let row=btn.closest('.setrow');let reps=row.querySelector('.reps');if(!reps.value){reps.focus();return}btn.classList.toggle('done');if(btn.classList.contains('done')){startTimer(type==='compound'?180:90);let wrap=btn.closest('.setwrap'),next=wrap.nextElementSibling;if(next){let kg=next.querySelector('.kg');if(kg&&!kg.value)kg.value=row.querySelector('.kg').value}}}

function runView(d){return `<h1>${d.name}</h1><p class='muted'>${d.duration}</p><div class='card'><div class='field'><label>Dauer (Minuten)</label><input id='runMin' type='number' value='35'></div><div class='field'><label>Distanz (km, optional)</label><input id='runKm' type='number' step='.01'></div><div class='field'><label>Notiz</label><textarea id='runNote'></textarea></div><button class='btn' onclick='saveRun()'>Lauf speichern</button></div>`}
function plan(){let d=PLAN[selected];return d.type==='run'?days()+`<div style='height:16px'></div>`+runView(d):strength(d)}
function progress(){let w=lastWeight();let names=[...new Set(db.sessions.flatMap(s=>(s.exercises||[]).map(e=>e.name)))],lastS=db.sessions.at(-1),vol=lastS?volume(lastS):0,prs=lastS?sessionPRs(lastS):0;return `<h1>Fortschritt</h1><div class='statline'><span class='stat'>Letztes Volumen: <b>${Math.round(vol).toLocaleString('de-DE')} kg</b></span><span class='stat pr'>${prs} PR${prs===1?'':'s'} im letzten Training</span></div><div class='grid'><div class='card'><div class='kicker'>Körpergewicht</div><div class='big'>${w.toFixed(1)} kg</div><div class='field'><label>Neues Gewicht</label><input id='newWeight' type='number' step='.1' value='${w}'></div><button class='btn small' onclick='addWeight()'>Eintragen</button></div><div class='card'><div class='kicker'>Trainings</div><div class='big'>${db.sessions.length}</div><div class='muted'>gespeicherte Krafteinheiten</div></div></div><div class='card weightlist'><div class='kicker'>Letzte Gewichtseinträge</div>${db.weight.slice(-5).reverse().map(x=>`<div class='weightrow'><span>${x.date}</span><b>${(+x.kg).toFixed(1)} kg</b></div>`).join('')}</div><h2 style='margin-top:22px'>Übungsverlauf</h2><div class='card'>${names.length?names.map(n=>{let entries=db.sessions.flatMap(s=>(s.exercises||[]).filter(e=>e.name===n).map(e=>({date:s.date,e})));let last=entries.at(-1);let best=Math.max(...entries.flatMap(z=>z.e.sets.map(s=>(+s.kg||0)*(1+(+s.reps||0)/30))));return `<div class='history'><b>${n}</b><div class='muted'>Letztes Training: ${last?.date||'-'} · geschätzter bester 1RM ${best?best.toFixed(1):'-'} kg</div></div>`}).join(''):'Noch keine Daten.'}</div>`}
function dataView(){return `<h1>Daten & Backup</h1><div class='card'><p>Deine Daten liegen lokal in diesem Browser. Exportiere regelmäßig ein Backup, besonders vor Handywechsel oder Löschen von Browserdaten.</p><div class='row'><button class='btn' onclick='exportData()'>Backup exportieren</button><label class='btn secondary'>Backup importieren<input type='file' accept='.json' style='display:none' onchange='importData(this)'></label></div></div><div class='card' style='margin-top:12px'><h3>Zurücksetzen</h3><button class='btn secondary' onclick='resetData()'>Alle Trainingsdaten löschen</button></div>`}
function render(){el().innerHTML=`<div class='shell'>${header()}${view==='home'?home():view==='plan'?plan():view==='progress'?progress():dataView()}</div>${nav()}`}
function finishWorkout(){let d=PLAN[selected],cards=[...document.querySelectorAll('.exercise')],exercises=cards.map(c=>({name:c.dataset.name,note:c.querySelector('.note').value,sets:[...c.querySelectorAll('.setrow')].map(r=>({kg:r.querySelector('.kg').value,reps:r.querySelector('.reps').value,rir:r.querySelector('.rir').value}))}));let s={date:today(),name:d.name,exercises};db.sessions.push(s);save();let p=sessionPRs(s);alert(`Training gespeichert ✓${p?` · ${p} neuer PR${p===1?'':'s'}`:''}`);view='home';render()}
function saveRun(){db.runs.push({date:today(),name:PLAN[selected].name,min:+document.getElementById('runMin').value,km:+document.getElementById('runKm').value||null,note:document.getElementById('runNote').value});save();alert('Lauf gespeichert ✓');view='home';render()}
function addWeight(){db.weight.push({date:today(),kg:+document.getElementById('newWeight').value});save();render()}function fmt(s){return `${Math.floor(s/60)}:${String(s%60).padStart(2,'0')}`}function paintTimer(){let box=document.getElementById('restFloat'),t=document.getElementById('timer');if(!box||!t)return;if(timerLeft>0){box.classList.add('show');t.textContent=fmt(timerLeft)}else{t.textContent='LOS';box.classList.add('show','ready')}}function startTimer(s){timerLeft=s;clearInterval(timer);paintTimer();timer=setInterval(()=>{timerLeft--;paintTimer();if(timerLeft<=0){clearInterval(timer);if(navigator.vibrate)navigator.vibrate([180,100,180]);setTimeout(()=>{let box=document.getElementById('restFloat');if(box)box.classList.remove('show','ready')},5000)}},1000)}function stopTimer(){clearInterval(timer);timerLeft=0;let box=document.getElementById('restFloat');if(box)box.classList.remove('show','ready')}
function exportData(){let a=document.createElement('a');a.href=URL.createObjectURL(new Blob([JSON.stringify(db,null,2)],{type:'application/json'}));a.download='85kg-workout-backup-'+today()+'.json';a.click()}function importData(i){let f=i.files[0];if(!f)return;let r=new FileReader;r.onload=()=>{try{db=JSON.parse(r.result);save();render();alert('Backup importiert ✓')}catch(e){alert('Ungültiges Backup')}};r.readAsText(f)}function resetData(){if(confirm('Wirklich alle Trainingsdaten löschen?')){localStorage.removeItem(K);location.reload()}}
render();
